name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v4

      - name: Deny banned crates and licenses
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Run linting and tests
        run: docker build --target tests -t tinty-clippy .
