name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v4

      - name: Deny banned crates and licenses
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Build clippy Stage
        run: docker build --target clippy -t tinty-clippy .

      - name: Build fmt stage
        run: docker build --target fmt -t tinty-fmt .

      - name: Build Test Stage
        run: docker build --target test -t tinty-test .
